source("C:\\MY_FOLDERS\\Asthma_and_Pain\\R_code\\Table_creation\\Set_of_functions.R")

# THIS sCRIPT USES THE REUSLTS FROM THE SCRIPT 'Table_20002.R'.
# FOR THIS SCRIPT TO WORK PROPERLY, YOU HAVE TO MAKE SURE THE LABELS PROVIDED HERE MATCH THE LABELS OF THE 
# TABLE(S) EXTRACTED WITH THE SCRIPT 'Table_20002.R'.

############################## NOT TO BE CHANGED #########################################################
n_visits <- 3 # The number of visits my go up to 4 when updates of the database is available
l_array <- 29  # there are 29 fields for conditions per visit
start_pos <- 5 # the columns with codes for conditions start with column 5 and end with columns 5+3*29-1 = 91  
##########################################################################################################


#######################  INPUTS FOR CONDITION SELECTION WITH AGE GROUPS  ##################################
# Choose one of the tables, generated by the script 'Table_20002.R' : 
t_cond <- t20002_bin

# Refer to the headers of either table t20002_bin, t20002_bin_reord or t20002_cond_age, 
# or alternatively, the script 'Table_20002.R' and the choose the label form the provided there
condition <- 'Asthma'

age_groups <- list(c(0,18), c(18,40), c(40, 120))

age_group_lbls <- c('Age_6', 'Age_4', 'Age_5' )

filepath_out <- "C:\\MY_FOLDERS\\Asthma_and_Pain\\Test_data\\condition_age_groups.txt"

############################## EXECUTE #############################################################
t_cond_agegrp_bin <- build_cond_agegrp_bin(t_cond, condition, age_groups, age_group_lbls, n_visits)

write.table(t_cond_agegrp_bin,
            filepath_out, 
            append = FALSE, sep = "\t", quote = FALSE, col.names=TRUE, row.names=FALSE)
